### ISSUE TITLE
[Android Bootcamp] Project 2 : Not yet ready...

### ISSUE THREAD

**Issue by tantofish** [tantofish/android_course_project2#1]
Hi Nidhi:
The deadline is on the corner, but I'm afraid that I'm not able to complete the assignment on time, mainly because of I went on a leave for the last couple of days. Is it ok to let me catch on those missed requirements in the weekend? thanks! 
/cc @codepathreview @codepath

**Comment by nidhi1608** [comment]
Hi Yu,

Since this is the first time you have missed the deadline, I can grant you an extension. It'll be great if you can submit this assignment by Sunday night at 10pm. However, I must warn you that you are going to have a pretty busy week since the next assignment for week 3 will also require some time. So you may have to start working on it from Monday onwards if you don't want to miss the deadline next week. Let me know if there is anything else I can do for you or if you have any questions.

**Comment by tantofish** [comment]
Thanks Nidhi, I'll make sure every requirements are achieved and try to complete the advances.
